# Generated by Django 3.2.5 on 2021-07-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cena_kgh', models.FloatField()),
                ('cena_pkn', models.FloatField()),
                ('cena_sen', models.FloatField()),
            ],
        ),
    ]
