# Generated by Django 3.2.5 on 2021-07-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='cena_kgh',
            new_name='Cena_KGH',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='cena_pkn',
            new_name='Cena_PKN',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='cena_sen',
            new_name='Cena_SEN',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='data',
            new_name='Data',
        ),
    ]
